name: Feature request
description: Funksiya təklifi
labels: [enhancement]
body:
  - type: textarea
    id: why
    attributes:
      label: Niyə lazımdır?
      description: Nəticə necə ölçüləcək?
      placeholder: Motivasiya və ölçülə bilən nəticə
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: Təklif olunan həll
      placeholder: Yaklaşım, təsvir, qəbul meyarları
    validations:
      required: true
