name: pr-codeowners-soft
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Soft CODEOWNERS note
        run: echo "ℹ Soft check: CODEOWNERS varsa PR-da reviewer görünməlidir."
