name: pr-guard-soft
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "ℹ Soft guard: PR title konvensiyası və etiketlər yoxlanır (no-fail)."
