name: release-drafter
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: read
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
